name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the short SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Determine tag
        id: tag_var
        run: |
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=${{ env.GIT_SHA }}" >> $GITHUB_ENV
          fi

      - name: downcase repo
        run: |
          REPO="${{ github.repository }}"
          echo "REPO=${REPO,,}" >> $GITHUB_ENV

      - name: Build and push docker image
        run: |
          set -e
          docker build -t outlinewiki/outline-base -f Dockerfile.base .
          docker build -t ghcr.io/${{ env.REPO }}:${{ env.TAG }} .
          docker push ghcr.io/${{ env.REPO }}:${{ env.TAG }}
